// Hand-reconstructed Supabase schema types.
//
// IMPORTANT: this file was NOT generated by introspecting your live
// database — I don't have network access or your project credentials in
// this environment. It was built by cross-referencing every migration
// I've written for this project and every query in the actual codebase,
// which is a solid approximation but not a guarantee of 100% accuracy.
//
// For the real thing, run this once you can (takes under a minute):
//
//   npx supabase login
//   npx supabase gen types typescript --project-id <your-project-ref> --schema public > src/lib/database.types.ts
//
// Your project ref is in the Supabase dashboard URL:
// https://supabase.com/dashboard/project/<this-part>
//
// Running that will OVERWRITE this file with a guaranteed-accurate
// version in the same shape, so nothing else in the codebase needs to
// change when you do.
//
// Note on `Relationships: []`: every table below needs this field even
// though it's always empty here — @supabase/supabase-js's internal
// GenericTable type requires it to resolve Row/Insert/Update types at
// all. Without it, TypeScript silently collapses every insert/update to
// `never`. An empty array is a safe default; it just means typed
// embedded-resource joins (e.g. .select("*, properties(*)") inferring
// the join shape automatically from a foreign key) won't be perfectly
// typed — the manual "could be array or object" handling already in
// profile/unlocked/page.tsx covers exactly that gap.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      properties: {
        Row: {
          id: string;
          created_at: string;
          title: string;
          description: string | null;
          address: string;
          category: string;
          school_tag: string;
          location: string;
          price: number;
          room_count: number | null;
          occupants_per_room: number | null;
          bathroom_count: number | null;
          latitude: number;
          longitude: number;
          landlord_phone: string | null;
          landlord_whatsapp: string | null;
          caretaker_name: string | null;
          caretaker_phone: string | null;
          caretaker_whatsapp: string | null;
          image_url: string;
          images: string[] | null;
          amenities: string[] | null;
          is_verified: boolean;
          is_available: boolean;
          is_visible: boolean;
          is_active: boolean;
          verified_at: string | null;
          verified_by: string | null;
          last_confirmed_at: string | null;
          caretaker_email: string | null;
          caretaker_status_token: string | null;
          multiple_units_available: boolean;
        };
        Insert: {
          id?: string;
          created_at?: string;
          title: string;
          description?: string | null;
          address: string;
          category: string;
          school_tag: string;
          location: string;
          price: number;
          room_count?: number | null;
          occupants_per_room?: number | null;
          bathroom_count?: number | null;
          latitude: number;
          longitude: number;
          landlord_phone?: string | null;
          landlord_whatsapp?: string | null;
          caretaker_name?: string | null;
          caretaker_phone?: string | null;
          caretaker_whatsapp?: string | null;
          image_url: string;
          images?: string[] | null;
          amenities?: string[] | null;
          is_verified?: boolean;
          is_available?: boolean;
          is_visible?: boolean;
          is_active?: boolean;
          verified_at?: string | null;
          verified_by?: string | null;
          last_confirmed_at?: string | null;
          caretaker_email?: string | null;
          caretaker_status_token?: string | null;
          multiple_units_available?: boolean;
        };
        Update: {
          id?: string;
          created_at?: string;
          title?: string;
          description?: string | null;
          address?: string;
          category?: string;
          school_tag?: string;
          location?: string;
          price?: number;
          room_count?: number | null;
          occupants_per_room?: number | null;
          bathroom_count?: number | null;
          latitude?: number;
          longitude?: number;
          landlord_phone?: string | null;
          landlord_whatsapp?: string | null;
          caretaker_name?: string | null;
          caretaker_phone?: string | null;
          caretaker_whatsapp?: string | null;
          image_url?: string;
          images?: string[] | null;
          amenities?: string[] | null;
          is_verified?: boolean;
          is_available?: boolean;
          is_visible?: boolean;
          is_active?: boolean;
          verified_at?: string | null;
          verified_by?: string | null;
          last_confirmed_at?: string | null;
          caretaker_email?: string | null;
          caretaker_status_token?: string | null;
          multiple_units_available?: boolean;
        };
        Relationships: [];
      };

      contact_unlocks: {
        Row: {
          id: number;
          created_at: string;
          user_id: string;
          property_id: string;
          payment_reference: string;
          payment_method: string;
        };
        Insert: {
          id?: number;
          created_at?: string;
          user_id: string;
          property_id: string;
          payment_reference: string;
          payment_method?: string;
        };
        Update: {
          id?: number;
          created_at?: string;
          user_id?: string;
          property_id?: string;
          payment_reference?: string;
          payment_method?: string;
        };
        Relationships: [];
      };

      unlock_reports: {
        Row: {
          id: number;
          created_at: string;
          user_id: string;
          property_id: string;
          unlock_reference: string | null;
          issue_type: "wrong_number" | "listing_gone" | "other";
          note: string | null;
          status: "open" | "reviewing" | "resolved";
          resolved_at: string | null;
          resolution_note: string | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          user_id: string;
          property_id: string;
          unlock_reference?: string | null;
          issue_type: "wrong_number" | "listing_gone" | "other";
          note?: string | null;
          status?: "open" | "reviewing" | "resolved";
          resolved_at?: string | null;
          resolution_note?: string | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          user_id?: string;
          property_id?: string;
          unlock_reference?: string | null;
          issue_type?: "wrong_number" | "listing_gone" | "other";
          note?: string | null;
          status?: "open" | "reviewing" | "resolved";
          resolved_at?: string | null;
          resolution_note?: string | null;
        };
        Relationships: [];
      };

      waitlist_signups: {
        Row: {
          id: number;
          created_at: string;
          email: string;
          context: string | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          email: string;
          context?: string | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          email?: string;
          context?: string | null;
        };
        Relationships: [];
      };

      unlock_feedback: {
        Row: {
          id: number;
          created_at: string;
          user_id: string;
          property_id: string;
          response: "found_place" | "still_looking" | "no_response" | "listing_wrong";
        };
        Insert: {
          id?: number;
          created_at?: string;
          user_id: string;
          property_id: string;
          response: "found_place" | "still_looking" | "no_response" | "listing_wrong";
        };
        Update: {
          id?: number;
          created_at?: string;
          user_id?: string;
          property_id?: string;
          response?: "found_place" | "still_looking" | "no_response" | "listing_wrong";
        };
        Relationships: [];
      };

      availability_pings: {
        Row: {
          id: number;
          created_at: string;
          property_id: string;
          requested_by_user_id: string | null;
          status: "pending" | "confirmed_available" | "confirmed_taken";
          responded_at: string | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          property_id: string;
          requested_by_user_id?: string | null;
          status?: "pending" | "confirmed_available" | "confirmed_taken";
          responded_at?: string | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          property_id?: string;
          requested_by_user_id?: string | null;
          status?: "pending" | "confirmed_available" | "confirmed_taken";
          responded_at?: string | null;
        };
        Relationships: [];
      };

      saved_properties: {
        // Only user_id/property_id are ever actually queried anywhere in
        // the codebase — if there's an id/created_at column too (likely),
        // marking them optional here is harmless either way.
        Row: {
          id?: number;
          created_at?: string;
          user_id: string;
          property_id: string;
        };
        Insert: {
          id?: number;
          created_at?: string;
          user_id: string;
          property_id: string;
        };
        Update: {
          id?: number;
          created_at?: string;
          user_id?: string;
          property_id?: string;
        };
        Relationships: [];
      };

      profiles: {
        Row: {
          id: string;
          email: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };

      admins: {
        // Confirmed column: user_id (stored as text, per the existing
        // RLS policy's `(auth.uid())::text = user_id` cast). Any other
        // columns on this table aren't queried anywhere in the codebase,
        // so they're not modeled here.
        Row: {
          user_id: string;
        };
        Insert: {
          user_id: string;
        };
        Update: {
          user_id?: string;
        };
        Relationships: [];
      };

      error_logs: {
        Row: {
          id: number;
          created_at: string;
          source: string;
          route: string | null;
          message: string;
          stack: string | null;
          context: Json | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          source: string;
          route?: string | null;
          message: string;
          stack?: string | null;
          context?: Json | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          source?: string;
          route?: string | null;
          message?: string;
          stack?: string | null;
          context?: Json | null;
        };
        Relationships: [];
      };
    };

    // Recent versions of @supabase/supabase-js require the full
    // GenericSchema shape — Tables alone isn't enough, even if these are
    // all empty. Without them, TypeScript can't properly resolve the
    // client's generic types, and silently collapses row types to
    // `never` on .insert()/.update()/.upsert() calls throughout the
    // codebase.
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
